"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

def SumOfEvenFibsLessThan(n):
    current = 1
    previous = 0
    sum = 0

    while(current < n):
        if(current % 2 == 0):
            sum += current
        current = current + previous
        previous = current - previous
    return sum

print(SumOfEvenFibsLessThan(4000000))

assert SumOfEvenFibsLessThan(100) == 44
assert SumOfEvenFibsLessThan(4000000) == 4613732
